services:

    mrapps.backend.archive.builder:
        class: Mrapps\BackendBundle\Services\ArchiveBuilder
        arguments:
            - @doctrine.orm.entity_manager
            - @mrapps.backend.public_url_provider
            - @kernel

    mrapps.backend.merger:
        class: Mrapps\BackendBundle\Services\EntityMerger
        arguments:
            - @mrapps.backend.translator
            - @security.token_storage
            - @request_stack
            - @mrapps.backend.public_url_provider

    mrapps.backend.translator:
        class: Mrapps\BackendBundle\Services\Translator
        arguments:
            - @doctrine.orm.entity_manager

    mrapps.backend.fields.builder:
        class: Mrapps\BackendBundle\Fields\FieldBuilder
        arguments:
            - @mrapps.backend.fields.validator

    mrapps.backend.fields.validator:
        class: Mrapps\BackendBundle\Fields\Validator

    mrapps_backend:
        class: Mrapps\BackendBundle\Twig\MrappsBackendBundleTwigExtension
        arguments: ['@service_container']
        public: false
        tags:
            - { name: twig.extension }

    mrapps.backend.buildsidebar_command:
            class: Mrapps\BackendBundle\Command\BuildSidebarCommand
            arguments:  []
            tags:
                -  { name: console.command }

    mrapps.backend.generatepermissions_command:
            class: Mrapps\BackendBundle\Command\GeneratePermissionsCommand
            arguments:  []
            tags:
                -  { name: console.command }

    mrapps.backend.draft_listener:
            class: Mrapps\BackendBundle\EventListener\DraftListener
            tags:
                - { name: doctrine.event_listener, event: onFlush }

    mrapps.backend.languages:
            class: Mrapps\BackendBundle\Handler\LanguageHandler
            calls:
                    - [setRequest , ["@service_container"]]

    mrapps.backend.validate:
            class: Mrapps\BackendBundle\Handler\ValidateHandler

    mrapps.twig_extension:
            class: Mrapps\BackendBundle\Twig\LocalizedPath
            arguments: ['@request_stack', '@router']
            public: false
            tags:
                - { name: twig.extension }

    mrapps.backend.public_url_provider:
            class: Mrapps\BackendBundle\Services\PublicUrlProvider
            arguments:
                - '@request_stack'
                - '@mrapps.backend.parameters_handler'

    mrapps.backend.parameters_handler:
                class: Mrapps\BackendBundle\Services\ParametersHandler
                calls:
                    - [setParameters, ["@=service('kernel').getContainer().getParameterBag()"]]

    mrapps.backend.entities_provider:
            class: Mrapps\BackendBundle\Services\EntitiesProvider
            arguments:
                - '@doctrine.orm.entity_manager'

    mrapps.twig_extension.absolute_url:
            class: Mrapps\BackendBundle\Twig\AbsoluteUrl
            arguments: ['@mrapps.backend.public_url_provider']
            public: false
            tags:
                - { name: twig.extension }