services:

    mrapps.backend.merger:
        class: Mrapps\BackendBundle\Services\EntityMerger
        arguments:
            - @mrapps.backend.translator

    mrapps.backend.translator:
        class: Mrapps\BackendBundle\Services\Translator
        arguments:
            - @doctrine.orm.entity_manager

    mrapps.backend.fields.builder:
        class: Mrapps\BackendBundle\Fields\FieldBuilder
        arguments:
            - @mrapps.backend.fields.validator

    mrapps.backend.fields.validator:
        class: Mrapps\BackendBundle\Fields\Validator

    mrapps_backend:
        class: Mrapps\BackendBundle\Twig\MrappsBackendBundleTwigExtension
        arguments: ['@service_container']
        public: false
        tags:
            - { name: twig.extension }

    mrapps.backend.buildsidebar_command:
            class: Mrapps\BackendBundle\Command\BuildSidebarCommand
            arguments:  []
            tags:
                -  { name: console.command }

    mrapps.backend.generatepermissions_command:
            class: Mrapps\BackendBundle\Command\GeneratePermissionsCommand
            arguments:  []
            tags:
                -  { name: console.command }

    mrapps.backend.draft_listener:
            class: Mrapps\BackendBundle\EventListener\DraftListener
            tags:
                - { name: doctrine.event_listener, event: onFlush }

    mrapps.backend.languages:
            class: Mrapps\BackendBundle\Handler\LanguageHandler
            calls:
                    - [setRequest , ["@service_container"]]

    mrapps.backend.validate:
                class: Mrapps\BackendBundle\Handler\ValidateHandler
