<?php

namespace Mrapps\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImmagineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImmagineRepository extends EntityRepository
{
}
