<?php

namespace Mrapps\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Mrapps\BackendBundle\Entity\Permission;

/**
 * PermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionRepository extends EntityRepository
{
    public function clearPermissions() {

        $em = $this->getEntityManager();

        $q = $em->createQuery('delete from MrappsBackendBundle:Permission p where 1=1');
        $numDeleted = $q->execute();

        return $numDeleted;
    }

    public function addPermission($route = '', $role = '', $permissions = array(), $autoFlush = true) {

        $em = $this->getEntityManager();
        $route = trim($route);
        $role = trim($role);

        if(strlen($route) > 0 && strlen($role) > 0) {

            $p = $this->findOneBy(array('role' => $role, 'route' => $route));
            if(null == $p) {
                $p = new Permission();
                $p->setRoute($route);
                $p->setRole($role);
            }

            $canView = (isset($permissions['view'])) ? intval($permissions['view']) : 0;
            $canEdit = (isset($permissions['edit'])) ? intval($permissions['edit']) : 0;
            $canDelete = (isset($permissions['delete'])) ? intval($permissions['delete']) : 0;

            $p->setCanView($canView);
            $p->setCanEdit($canEdit);
            $p->setCanDelete($canDelete);

            $em->persist($p);
            if($autoFlush) {
                $em->flush($p);
            }

            return $p;
        }

        return null;
    }
}
